openapi: 3.0.3
info:
  title: Badminton Service API
  version: 0.0.1
tags:
  - name: TelegramAuth
paths:
  /api/auth/telegram/login:
    post:
      summary: Login via Telegram authorization data
      operationId: telegramLogin
      tags:
        - TelegramAuth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TelegramUser'
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelegramUser'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TelegramUser:
      type: object
      required:
        - id
        - auth_date
        - hash
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        photo_url:
          type: string
        auth_date:
          type: integer
          format: int64
        hash:
          type: string
    ErrorResponse:
      type: object
      required:
        - timestamp
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        path:
          type: string
